server:
  protocol: https
  hostname: ${API_HOSTNAME}
  port: ${PORT}
  adminPort: ${ADMIN_PORT}
  basePathPrefix: /api
  keyPath: /path/to/key.pem
  certPath: /path/to/server.crt
  secureProtocol: TLSv1_2_method

authentication:
  username: ${USER}
  password: ${PASSWD}

dataSources:
  dataSources: ['http']
  http:
    baseUri: ${ONBASE_BASE_URL}
    idpServer: ${ONBASE_IDP_SERVER}
    apiServer: ${ONBASE_API_SERVER}
    tenant: ${ONBASE_TENANT}
    clientId: ${ONBASE_CLIENT_ID}
    clientSecret: ${ONBASE_CLIENT_SECRET}
    onbaseProfiles:
      profile1:
        username: ${ONBASE_PROFILE1_USERNAME}
        password: ${ONBASE_PROFILE1_PASSWORD}

