apiBasePath: api/v1/onbase-docs
apiHost: https://api.oregonstate.edu
dataSource: testDatabaseName
serviceUrl: https://onbase-url.com
docIndexKeyName: Index Key Sample
stagingDocType: Staging Sample
port: ${PORT}
adminPort: ${ADMIN_PORT}
authentication:
  username: ${USER}
  password: ${PASSWD}
profiles:
  profile1:
    username: user
    password: pass
  profile2:
    username: user2
    password: pass2
